[project]
name = "Seekify"
version = "1.0.0"
description = "Search app for course project."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"